tokenize:
  limit: 10

#spring:
#  datasource:
#    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?reconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driver-class-name: "com.mysql.cj.jdbc.Driver"

#model:
#  url: https://hackday2019infer.herokuapp.com/score

spring:
  datasource:
    url: jdbc:mysql:///hackday2019?cloudSqlInstance=hackday2019-262006:asia-east1:word-category&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
    username: root
    password: ""
    driver-class-name: "com.mysql.cj.jdbc.Driver"

model:
  url: https://infer-dot-hackday2019-262006.appspot.com/score
