tokenize:
  limit: 10

spring:
  datasource:
    url: ${DATABASE_URL}
    #url: jdbc:mysql://localhost:3306/hackday2019
    #username: root
    #password: ""
    driver-class-name: "com.mysql.cj.jdbc.Driver"
