tokenize:
  limit: 10

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?reconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
