tokenize:
  limit: 10

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hackday2019
    username: root
    password: ""
    driver-class-name: "com.mysql.cj.jdbc.Driver"

model:
  url: https://hackday2019infer.herokuapp.com/score
